languageCode = "en"
languageName = "English"
weight = 1
title = "DREAMRUNNERS"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "images/paisley.png"
  # secondaryLogo = "images/logo.png"
  # description = "My awesome website"

 [author]
   name = "Dreamrunners"
   #image = "images/logo.jpg"
   headline = "An OK rockband."
   # bio = "Music. Stuff."
   links = [
     { email = "mailto:contact@dreamrunners.se" },
     { facebook = "https://facebook.com/dreamrunnersband" },
     { instagram = "https://instagram.com/dreamrunners_music" },
     { youtube = "https://youtube.com/dreamrunnersband" },
   ]
