languageCode = "en"
languageName = "English"
weight = 1
title = "DREAMRUNNERS"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "images/logo.jpg"
  # secondaryLogo = "images/logo.png"
  # description = "My awesome website"
  copyright = "© Dreamrunners 2024. Photo credit (backgrounds): Florence Stadelmann"

 [author]
   name = "Dreamrunners"
   image = "images/logo.jpg"
   headline = "An energetic rock band with Swedish roots and some Italian spice."
   # bio = "Music. Stuff."
   links = [
     { email = "mailto:contact@dreamrunners.se" },
     { facebook = "https://www.facebook.com/profile.php?id=61556890701699" },
     { instagram = "https://instagram.com/dreamrunners_music" },
     { youtube = "https://www.youtube.com/@Dreamrunners_music/" },
   ]
