languageCode = "en"
languageName = "English"
weight = 1
title = "DREAMRUNNERS"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "images/logo.png"
  # secondaryLogo = "images/logo.png"
  description = "Official website for the Swedish rock band Dreamrunners."
  copyright = "© Dreamrunners 2024"

 [author]
   name = " "
   # image = "images/logo.jpg"
   headline = "A high-energy rock band with Swedish heritage and a touch of Italian zest."
   # bio = "Music. Stuff."
   links = [
     { instagram = "https://instagram.com/dreamrunners_music" },
     { facebook = "https://www.facebook.com/profile.php?id=61556890701699" },
     { youtube = "https://www.youtube.com/@Dreamrunners_music/" },
   ]
