[[main]]
  name = "GIGS"
  pageRef = "gigs"
  weight = 10

[[main]]
  name = "ABOUT"
  pageRef = "band"
  weight = 20

[[main]]
  name = "DREAMRUNNERS"
  parent = "ABOUT"
  pageRef = "band"
  weight = 21

[[main]]
  name = "JACOB"
  parent = "ABOUT"
  pageRef = "authors/jacob"
  weight = 21
  
[[main]]
  name = "JOHAN"
  parent = "ABOUT"
  pageRef = "authors/johan"
  weight = 22

[[main]]
  name = "FREDRIK"
  parent = "ABOUT"
  pageRef = "authors/fredrik"
  weight = 23

[[main]]
  name = "NIC"
  parent = "ABOUT"
  pageRef = "authors/nic"
  weight = 24

[[main]]
  name = "BOOKING/CONTACT"
  pageRef = "contact"
  weight = 30
