[[main]]
  name = "Gigs"
  pageRef = "gigs"
  weight = 10

[[main]]
  name = "Media"
  pageRef = "media"
  weight = 15

[[main]]
  name = "Shop"
  pageRef = "shop"
  weight = 17

[[main]]
  name = "Booking/Contact"
  pageRef = "contact"
  weight = 19

[[main]]
  name = "About"
  pageRef = "band"
  weight = 20

[[main]]
  name = "Dreamrunners"
  parent = "About"
  pageRef = "band"
  weight = 21

[[main]]
  name = "Jacob"
  parent = "About"
  pageRef = "authors/jacob"
  weight = 22
  
[[main]]
  name = "Johan"
  parent = "About"
  pageRef = "authors/johan"
  weight = 23

[[main]]
  name = "Fredrik"
  parent = "About"
  pageRef = "authors/fredrik"
  weight = 24

[[main]]
  name = "Nic"
  parent = "About"
  pageRef = "authors/nic"
  weight = 25
